### ISSUE TITLE
Keep minimal dependencies

### ISSUE THREAD

**Issue by cy-long** [MITEcology/feasibility_analysis#4]
There are one dependency that is used only twice in several new functions:

`#' @importFrom matlib inv`

And when I call matlib on my machine, it causes errors. I believe it is related to the fact that matlib also has 3D visualization functions, which depend on the `rgl` package and XQuartz on macOS. Missing these environments causes errors.

To my understanding, we are using`matlib::inv` in only two places to inverse a matrix. If there's no special needs on that (for example, if  matlib::inv is the only one that could deal with this type of matrix inversion), I would recommend using `pracma::inv`.

**Comment by cy-long** [comment]
For the moment, I already replaced`matlib::inv` with `pracma::inv` in commit 97d55f4

**Comment by ibartomeus** [comment]
Great idea, the lighter the package, the better. It also took me a while to install rgl properly.
